language: python

python:
  - "2.7"

install:
  - "pip install -e .[tests]"

script:
  - make tests

notifications:
  email:
    - luper.rouch@gmail.com
  slack:
    secure: PI9aXnjvFEt84LIhaFgvuXLUojbfbWxKB4H3R4mQk4mxuYPiap+1kdccM6lA8RiRFF74ia7qGE6ctfSGUQ34Gt23b1ZbUubQO0KHjowQBLesAl2V2ENNVgguVTUYTy4sHNy7EVS68eAwJFbCk/0wfqtY8ed4mAqttTudqig2/V0=
