language: python

python:
  - "2.7"

env:
  - DEFAULT_DB=mysql
  - DEFAULT_DB=postgres

services:
  - mysql
  - postgresql
  - redis-server

install:
  - "pip install -e .[$DEFAULT_DB,tests]"

before_script:
  - mysql -e 'create database sentry;'
  - psql -c 'create database sentry;' -U postgres

script:
  - make tests

notifications:
  email:
    - luper.rouch@gmail.com
  slack:
    secure: PI9aXnjvFEt84LIhaFgvuXLUojbfbWxKB4H3R4mQk4mxuYPiap+1kdccM6lA8RiRFF74ia7qGE6ctfSGUQ34Gt23b1ZbUubQO0KHjowQBLesAl2V2ENNVgguVTUYTy4sHNy7EVS68eAwJFbCk/0wfqtY8ed4mAqttTudqig2/V0=
